### ISSUE TITLE
when I start hipache ,there is an error

### ISSUE THREAD

**Issue by kaka3052** [hipache/hipache#16]
when I start hipache ,there is an error,
anybody has the same error?

root@AY121114091050444f816:/usr/local/lib/node_modules/hipache/config# hipache
30 Jan 11:14:12 - Loading config from /usr/local/lib/node_modules/hipache/config/config.json
30 Jan 11:14:12 - Spawning worker #0
30 Jan 11:14:12 - Server is running. {"debug":true,"accessLog":"/tmp/proxy2_test_access.log","port":80,"workers":1,"maxSockets":100,"deadBackendTTL":30,"tcpTimeout":50,"retryOnError":30,"httpKeepAlive":false,"lruCache":{"size":5,"ttl":5}}
30 Jan 11:14:12 - Loading config from /usr/local/lib/node_modules/hipache/config/config.json
30 Jan 11:14:12 - (worker #19334) Cache: LRU cache is enabled

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRNOTAVAIL
    at errnoException (net.js:769:11)
    at Server._listen2 (net.js:892:19)
    at net.js:933:12
    at Object.cluster._getServer (cluster.js:555:5)
    at handleResponse (cluster.js:149:41)
    at respond (cluster.js:170:5)
    at handleMessage (cluster.js:180:5)
    at process.EventEmitter.emit (events.js:126:20)
    at handleMessage (child_process.js:269:12)
    at Pipe.channel.onread (child_process.js:293:9)
30 Jan 11:14:12 - Worker died (pid: 19334, suicide: false, exitcode: 1). Spawning a new one.

**Comment by dcarley** [comment]
We also got this error when using the 0.2.5 package from Tsuru on a Ubuntu 14.04 instance in Google Compute Engine. It was caused by IPv6 being disabled by default and the machine having no link-local v6 addresses. The solution was to change the configuration to not attempt to bind v6 with: `"address6": []`
