### ISSUE TITLE
Document how to run tests and how to contribute?

### ISSUE THREAD

**Issue by msabramo** [hipache/hipache#194]
I want to be able to contribute more effectively, but I'm not experience with node.js.

I'm trying to run the tests on OS X 10.9.5 and running into problems.

```
[marca@marca-mac2 hipache]$ npm test

> hipache@0.4.0 test /Users/marca/dev/git-repos/hipache
> istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 4000



  1) "before all" hook

  0 passing (4s)
  1 failing

  1)  "before all" hook:
     Uncaught Error: spawn ENOENT
      at errnoException (child_process.js:1011:11)
      at Process.ChildProcess._handle.onexit (child_process.js:802:34)



npm ERR! Test failed.  See above for more details.
```

What does this error mean? How do I get the tests to run?

**Comment by willdurand** [comment]
It is documented but definitely not easy to use.

Such an error might mean that you don't have `redis-server` available on your system.

**Comment by willdurand** [comment]
See:

* https://github.com/hipache/hipache/blob/master/test/README.md
* https://github.com/hipache/hipache/blob/master/test/functional/README.md

**Comment by msabramo** [comment]
Thanks! I didn't see those files. I guess I expected them to be in the `README.md` in the root directory. Not a bad idea to have them in a special place, though I think I might add a link to the main `README.md` to make them more discoverable. See https://github.com/hipache/hipache/pull/197

**Comment by msabramo** [comment]
I don't think it's `redis-server` as that is getting launched (and also not cleaned up; which I should add to #195).

```
[marca@marca-mac2 hipache]$ pgrep -fl redis
22379 /usr/local/opt/redis/bin/redis-server 127.0.0.1:6379
[marca@marca-mac2 hipache]$ npm test

> hipache@0.4.0 test /Users/marca/dev/git-repos/hipache
> istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 4000



  1) "before all" hook

  0 passing (4s)
  1 failing

  1)  "before all" hook:
     Uncaught Error: spawn ENOENT
      at errnoException (child_process.js:1011:11)
      at Process.ChildProcess._handle.onexit (child_process.js:802:34)



npm ERR! Test failed.  See above for more details.
[marca@marca-mac2 hipache]$ pgrep -fl redis
22379 /usr/local/opt/redis/bin/redis-server 127.0.0.1:6379
65544 redis-server *:7777
65552 redis-server *:7001
65554 redis-server *:7002
65555 redis-server *:7003
```

It must be some other process it's trying to launch, but unfortunately the error message is not terribly helpful.

I think it's not:

- redis-server
- memcached
- hipache

Maybe zookeeper or etcd as IIRC I saw some references to those.

**Comment by willdurand** [comment]
Then try to disable them with NO_ETCD and NO_ZOOKEEPER env vars (see travis-ci file)

**Comment by msabramo** [comment]
It appears to be zookeeper that's causing the problem for me on OS X. When I set `NO_ZOOKEEPER=1`, then the `spawn` error goes away (though I'm now getting  a bunch of failures in memcached tests that all say `Error: timeout of 2000ms exceeded`).

This is on OS X 10.9.5 and I've installed zookeeper with homebrew.

**Comment by dmp42** [comment]
Disable them all if you don't have any installed.
eg:  `NO_MEMCACHED=true NO_ETCD=true NO_ZOOKEEPER=true npm test`

**Comment by msabramo** [comment]
I have all of those installed actually. But for some reason I get problems with some of them. I don't know why yet.

**Comment by willdurand** [comment]
look at the `test/fixtures/services/zookeeper` file then

**Comment by msabramo** [comment]
Looks probably related that Homebrew renames `zkServer` to `zkServer.sh`?

```
[marca@marca-mac2 hipache]$ which zkServer.sh
zkServer.sh not found
[marca@marca-mac2 hipache]$ which zkServer
/usr/local/bin/zkServer
[marca@marca-mac2 hipache]$ zkServer
JMX enabled by default
Using config: /usr/local/etc/zookeeper/zoo.cfg
Usage: ./zkServer.sh {start|start-foreground|stop|restart|status|upgrade|print-cmd}
```

Made a symlink and then the spawn error goes away and I get a timeout error:

```
[marca@marca-mac2 hipache]$ sudo ln -s zkServer /usr/local/bin/zkServer.sh

[marca@marca-mac2 hipache]$ zkServer.sh
JMX enabled by default
Using config: /usr/local/etc/zookeeper/zoo.cfg
Usage: ./zkServer.sh {start|start-foreground|stop|restart|status|upgrade|print-cmd}

[marca@marca-mac2 hipache]$ npm test

> hipache@0.4.0 test /Users/marca/dev/git-repos/hipache
> istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 4000



ERR! Server#zkServer.sh  JMX enabled by default
ERR! Server#zkServer.sh
ERR! Server#zkServer.sh  Using config: /Users/marca/zookeeper/zoo.cfg
ERR! Server#zkServer.sh
  1) "before all" hook
  2) "after all" hook

  0 passing (14s)
  2 failing

  1)  "before all" hook:
     Error: timeout of 4000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2)  "after all" hook:
     Error: timeout of 4000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



npm ERR! Test failed.  See above for more details.
```

**Comment by willdurand** [comment]
and disabling zookeeper does not work?

**Comment by msabramo** [comment]
Well, it does get rid of the zookeeper failures, but then I get etcd and memcached failures and not because I don't have them installed.

e.g.:

```
...
  1) Etcd etcd://:8001 Domain with no match, no fallback:

      Uncaught AssertionError: expected [ Array(3) ] to deeply equal [ [], [], [] ]
      + expected - actual

       [
         []
      -  [
      -    "supervhost"
      -    "backend:910"
      -  ]
         []
      +  []
       ]

      at /Users/marca/dev/git-repos/hipache/test/unit/driver-test-reading.js:20:33
      at lookup (/Users/marca/dev/git-repos/hipache/lib/drivers/etcd.js:108:21)
      at /Users/marca/dev/git-repos/hipache/lib/drivers/etcd.js:118:21
      at Client._handleResponse (/Users/marca/dev/git-repos/hipache/node_modules/node-etcd/lib/client.js:78:14)
      at Request._callback (/Users/marca/dev/git-repos/hipache/node_modules/node-etcd/lib/client.js:32:22)
      at Request.self.callback (/Users/marca/dev/git-repos/hipache/node_modules/node-etcd/node_modules/request/request.js:122:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/node-etcd/node_modules/request/request.js:888:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/node-etcd/node_modules/request/request.js:839:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)
...
  19) Memcached memcached://:9001/#prefix,memcached://:9002/#prefix Single domain with multiple backends and fallback plus a second dead:
     Error: timeout of 4000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by msabramo** [comment]
OK, well this works:

```
$ NO_ETCD=true NO_MEMCACHED=true NO_ZOOKEEPER=true npm test
```

but it's curious that I have to disable 3 things to get the tests to pass. Thought it may very well be a configuration problem on my system.

**Comment by msabramo** [comment]
Interesting that when I run without `NO_ZOOKEEPER=true`, it fails but it is definitely able to talk to Zookeeper, because it leaves it running after the test errors out (https://github.com/hipache/hipache/issues/195):

```
[marca@marca-mac2 hipache]$ pgrep -fl 'memcache'; pgrep -fl 'redis-server'; pgrep -fl 'hipache'; pgrep -fl 'zookeeper'; pgrep -fl 'etcd'
[marca@marca-mac2 hipache]$ npm test

> hipache@0.4.0 test /Users/marca/dev/git-repos/hipache
> istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 4000



ERR! Server#zkServer.sh  JMX enabled by default
ERR! Server#zkServer.sh
ERR! Server#zkServer.sh  Using config: /Users/marca/zookeeper/zoo.cfg
ERR! Server#zkServer.sh
  1) "before all" hook
  2) "after all" hook

  0 passing (14s)
  2 failing

  1)  "before all" hook:
     Error: timeout of 4000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2)  "after all" hook:
     Error: timeout of 4000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



npm ERR! Test failed.  See above for more details.
[marca@marca-mac2 hipache]$ pgrep -fl 'memcache'; pgrep -fl 'redis-server'; pgrep -fl 'hipache'; pgrep -fl 'zookeeper'; pgrep -fl 'etcd'
28552 /usr/bin/java -Dzookeeper.log.dir=/Users/marca/zookeeper/ -Dzookeeper.root.logger=INFO,CONSOLE -cp /usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/classes:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../build/lib/*.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-log4j12-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/slf4j-api-1.6.1.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/netty-3.7.0.Final.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/log4j-1.2.16.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../lib/jline-0.9.94.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../zookeeper-3.4.6.jar:/usr/local/Cellar/zookeeper/3.4.6_1/libexec/bin/../src/java/lib/*.jar:/usr/local/etc/zookeeper: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /Users/marca/zookeeper/zoo.cfg
```

**Comment by msabramo** [comment]
I also tried raising the timeout from 4000ms to 16000ms and that didn't help.

```
[marca@marca-mac2 hipache]$ git diff
diff --git a/package.json b/package.json
index c05b7dd..7bdadfc 100644
--- a/package.json
+++ b/package.json
@@ -48,7 +48,7 @@
   },
   "scripts": {
     "start": "./bin/hipache",
-    "test": "istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 4000",
+    "test": "istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 16000",
     "coveralls": "istanbul cover _mocha --report lcovonly -- test/**/*.js -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage",
     "hint": "gulp hint"
   },
[marca@marca-mac2 hipache]$ npm test

> hipache@0.4.0 test /Users/marca/dev/git-repos/hipache
> istanbul test _mocha --report html -- test/**/*.js --reporter spec --timeout 16000



ERR! Server#zkServer.sh  JMX enabled by default
ERR! Server#zkServer.sh
ERR! Server#zkServer.sh  Using config: /Users/marca/zookeeper/zoo.cfg
ERR! Server#zkServer.sh
  1) "before all" hook
  2) "after all" hook

  0 passing (37s)
  2 failing

  1)  "before all" hook:
     Error: timeout of 16000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2)  "after all" hook:
     Error: timeout of 16000ms exceeded
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



npm ERR! Test failed.  See above for more details.
```

**Comment by msabramo** [comment]
Working on adding a `CONTRIBUTING.md` file in https://github.com/hipache/hipache/pull/197

**Comment by dmp42** [comment]
etcd and memcached should be fixed by the PR I submitted.
I'm looking into zk now.

**Comment by msabramo** [comment]
I think I see the problem - comma instead of space in the `zkServer.sh` command. I'll send a PR later.

**Comment by msabramo** [comment]
comma/space thing was a red herring.

**Comment by msabramo** [comment]
Just updated #197
