### ISSUE TITLE
AssertionError: false == true

### ISSUE THREAD

**Issue by FLYBYME** [hipache/hipache#218]
Getting this error

```
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at SharedHandle.add (cluster.js:97:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
``
```
$ node -v
v0.12.0
```

**Comment by dmp42** [comment]
0.12 is untested so far.
I would recommend you stick with 0.10 until 0.12 received proper testing.
Thanks for this, though, it will help!
