### ISSUE TITLE
The driver for etcd: is likely broken

### ISSUE THREAD

**Issue by DimShadoWWW** [hipache/hipache#220]
Hello, I clonned the git repository, make a docker image, changed the config to:
```
{
    "server": {
        "accessLog": "/var/log/hipache/hipache.log",
        "workers": 10,
        "maxSockets": 100,
        "deadBackendTTL": 30,
        "tcpTimeout": 30,
        "retryOnError": 3,
        "deadBackendOn500": true,
        "httpKeepAlive": false,
        "staticDir": null
    },
    "http": {
        "port": 80,
        "bind": [ "0.0.0.0" ]
    },
    "driver": ["etcd://172.17.42.1:4001"]
}
```
but the container fails with this error showing again and again:
```
DriverError: The driver for etcd: is likely broken (TypeError: object is not a function)
    at getDriver (/usr/local/lib/node_modules/hipache/lib/drivers/factory.js:48:21)
    at new Cache (/usr/local/lib/node_modules/hipache/lib/cache.js:72:27)
    at Cache (/usr/local/lib/node_modules/hipache/lib/cache.js:54:16)
    at new Worker (/usr/local/lib/node_modules/hipache/lib/worker.js:61:18)
    at null.<anonymous> (/usr/local/lib/node_modules/hipache/bin/hipache:70:21)
    at g (events.js:180:16)
    at EventEmitter.emit (events.js:92:17)
    at null.<anonymous> (/usr/local/lib/node_modules/hipache/lib/config/config.js:61:18)
    at process._tickCallback (node.js:415:13)
26 Mar 11:17:10 - Loading config from /usr/local/lib/node_modules/hipache/config/config.json
DriverError: The driver for etcd: is likely broken (TypeError: object is not a function)
    at getDriver (/usr/local/lib/node_modules/hipache/lib/drivers/factory.js:48:21)
    at new Cache (/usr/local/lib/node_modules/hipache/lib/cache.js:72:27)
    at Cache (/usr/local/lib/node_modules/hipache/lib/cache.js:54:16)
    at new Worker (/usr/local/lib/node_modules/hipache/lib/worker.js:61:18)
    at null.<anonymous> (/usr/local/lib/node_modules/hipache/bin/hipache:70:21)
    at g (events.js:180:16)
    at EventEmitter.emit (events.js:92:17)
    at null.<anonymous> (/usr/local/lib/node_modules/hipache/lib/config/config.js:61:18)
    at process._tickCallback (node.js:415:13)
26 Mar 11:17:10 - Worker died (pid: 90, suicide: false, exitcode: 8). Spawning a new one.
26 Mar 11:17:10 - Worker died (pid: 101, suicide: false, exitcode: 8). Spawning a new one.
DriverError: The driver for etcd: is likely broken (TypeError: object is not a function)
    at getDriver (/usr/local/lib/node_modules/hipache/lib/drivers/factory.js:48:21)
    at new Cache (/usr/local/lib/node_modules/hipache/lib/cache.js:72:27)
```

**Comment by dmp42** [comment]
How was this installed?

**Comment by DimShadoWWW** [comment]
I cloned the github repository, edited the config file and created the docker image from the included Dockerfile

**Comment by kgorskowski** [comment]
+1 here - any suggestions on how to fix this? am I missing something?

**Comment by llonchj** [comment]
hipache@0.3.1 and node-etcd@3.0.2 works for me
