### ISSUE TITLE
Cannot start hipache - Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by shanmugakarna** [hipache/hipache#225]
I'm getting the following error, while running Hipache. Earlier version, which i installed 1 week back is working fine.

util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:555:43)
    at Object.<anonymous> (/opt/hipache/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/hipache/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)

**Comment by nathwill** [comment]
it's due to eventemitter3, see https://github.com/hipache/hipache/issues/223

**Comment by stackexpress-varun** [comment]
I too not able to run Hipache from it's docker image `hipache:0.3.1`(latest). I get the same error `TypeError: Cannot read property 'prototype' of undefined`.
 
Please have a look at docker image  `hipache:latest`.

**Comment by pirog** [comment]
Can confirm this and that downgrading http-proxy resolves. Also https://github.com/hipache/hipache/pull/224 seems like a good idea.

**Comment by trsouz** [comment]
I'm having this problem using the image of Docker. I tested upgrading http-proxy to the stable version 1.11.1 and apparently solved the problem.

**Comment by robsonpeixoto** [comment]
I'm having the same problem. How can I solve it?

**Comment by dmitryck** [comment]
@trsouz what did you mean "upgrading http-proxy to the stable version 1.11.1"
http-proxy is the a some package?

**Comment by trsouz** [comment]
Yes @dmitryck, http-proxy is a hipache dependence. See https://github.com/hipache/hipache/blob/master/package.json#L25

This update work for me. See my fork: https://github.com/trsouz/hipache/commit/f221bca2d947b1604af1657164788ab575aa9f0a
And I think that is affecting all versions of hipache. See the travis with current commit: https://travis-ci.org/trsouz/hipache/builds/61718250

And travis with my update: https://travis-ci.org/trsouz/hipache/builds/61717531

**Comment by mamciek** [comment]
after updating http-proxy i have problem with headers x-forwarded-proto. My Nginx that request is forwarded to doesn't see them somehow

**Comment by mamciek** [comment]
It only happens with nodejs 0.12. It might be related: https://github.com/nodejitsu/node-http-proxy/issues/772

**Comment by prologic** [comment]
+1 confirmed here too

**Comment by kolis** [comment]
+1
