### ISSUE TITLE
Looping errors in terminal out and could not start hipache!

### ISSUE THREAD

**Issue by dmitryck** [hipache/hipache#227]
I have a very strange trouble...

When a start hipache - there is some none-stop loop of errors in terminal window..  it means that hipache do some code and repeat it again and again... and could not start((

Anyone has something like this trouble??

There is a part of looped terminal out:
------------------------------------

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.150:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:20 - Worker died (pid: 2013, suicide: false, exitcode: 8). Spawning a new one.
19 May 19:09:21 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:21 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:21 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:21 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json

events.js:72
        throw er; // Unhandled 'error' event
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json
              ^

Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.151:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
events.js:72
        throw er; // Unhandled 'error' event
              ^
19 May 19:09:22 - Worker died (pid: 2015, suicide: false, exitcode: 8). Spawning a new one.
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.152:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:22 - Worker died (pid: 2016, suicide: false, exitcode: 8). Spawning a new one.
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.153:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:22 - Worker died (pid: 2019, suicide: false, exitcode: 8). Spawning a new one.

events.js:72
        throw er; // Unhandled 'error' event
              ^
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.154:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:22 - Worker died (pid: 2020, suicide: false, exitcode: 8). Spawning a new one.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.155:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:22 - Worker died (pid: 2022, suicide: false, exitcode: 8). Spawning a new one.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.156:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:22 - Worker died (pid: 2023, suicide: false, exitcode: 8). Spawning a new one.
19 May 19:09:22 - Loading config from /usr/lib/node_modules/hipache/config/config.json

events.js:72
        throw er; // Unhandled 'error' event
              ^

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.157:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.158:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:23 - Worker died (pid: 2027, suicide: false, exitcode: 8). Spawning a new one.
19 May 19:09:23 - Worker died (pid: 2028, suicide: false, exitcode: 8). Spawning a new one.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.159:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:23 - Worker died (pid: 2031, suicide: false, exitcode: 8). Spawning a new one.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.160:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
19 May 19:09:23 - Worker died (pid: 2033, suicide: false, exitcode: 8). Spawning a new one.
19 May 19:09:24 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:24 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:24 - Loading config from /usr/lib/node_modules/hipache/config/config.json
19 May 19:09:24 - Loading config from /usr/lib/node_modules/hipache/config/config.json
^C19 May 19:09:24 - Exiting, killing the workers
19 May 19:09:24 - Killing worker #2035
19 May 19:09:24 - Killing worker #2036
19 May 19:09:24 - Killing worker #2039
19 May 19:09:24 - Killing worker #2040
19 May 19:09:24 - Killing worker #2042
19 May 19:09:24 - Killing worker #2044
19 May 19:09:24 - Killing worker #2047
19 May 19:09:24 - Killing worker #2048
19 May 19:09:24 - Killing worker #2051
19 May 19:09:24 - Killing worker #2053

---------

What is it?
THANX!

**Comment by Starefossen** [comment]
Looks like the port (80 and/or 443) is already in use
