### ISSUE TITLE
Hipache command not working 

### ISSUE THREAD

**Issue by kgrvamsi** [hipache/hipache#230]
util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/usr/lib/node_modules/hipache/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/hipache/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)

**Comment by sdwr98** [comment]
See this issue: https://github.com/hipache/hipache/issues/223.

**Comment by kgrvamsi** [comment]
@sdwr98  this error happens even if i run the official docker image from the docker hub.Can we have a fixed version of the Docker image in registry?
