### ISSUE TITLE
cannot get hipache to work

### ISSUE THREAD

**Issue by thecodeassassin** [hipache/hipache#235]
Node version: $ node -v
v4.1.2

NPM version: $ npm -v
2.14.4

$ hipache
util.js:731
    throw new TypeError('The super constructor to `inherits` must not ' +
    ^

TypeError: The super constructor to `inherits` must not be null or undefined.
    at Object.exports.inherits (util.js:731:11)
    at Object.<anonymous> (/usr/lib/node_modules/hipache/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/hipache/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:434:26)

**Comment by shanmugakarna** [comment]
Me too facing the same issue.. Any solutions yet

**Comment by travisby** [comment]
(user, not maintainer) - I've seen this with different versions of node-http-proxy, while running on node 0.10 or 0.12.  We upgraded to:

+    "http-proxy": "^1.11.0",

and it alleviated our problems.

(Note, we did this about a year ago, so not sure if the landscape is still the same.  Good luck!)

**Comment by skarungan** [comment]
The issue gets solved by using 1.11.1 version of http-proxy as @travisby has said.

**Comment by relvacode** [comment]
Facing same issue as well with npm installed hipache on Fedora 23. Manually installing the latest http-proxy (1.12.0) resolved this issue.

npm: 3.3.12
node: v5.3.0
system: 4.2.6-301.fc23.x86_64

Could the package.json please get updated to fix this?
